/**
 * agent-handoff — Phase 5 (2026-05-02).
 *
 * `generateHandoff(spec, productState) → string` returns the full Markdown
 * `agent-handoff.md` content a coding agent (Claude Code, Cursor, Codex)
 * pastes directly. The handoff is the artifact the entire adaptive-intake
 * flow exists to deliver.
 *
 * Section ordering is INTENTIONALLY prompt-cache-friendly:
 *
 *   1. Build objective + persona + non-goals     ← stable identity
 *   2. Stance + tradeoff weights                 ← stable strategic frame
 *   3. ADRs + data model + API contracts          ← architecture (changes slowly)
 *   4. Platform-specific test scaffolding         ← per-target build instructions
 *   5. Ask-before policy                          ← guardrails (verbatim)
 *   6. Specific Needs / Features / UX flows       ← dynamic specifics last
 *   7. Assumptions + risks                        ← dynamic
 *
 * Anthropic prompt caching keys on identical leading prefix — putting
 * identity content first means a re-paste with edits at the bottom keeps
 * the cache warm.
 *
 * Security:
 *   - Caller is expected to scrub PII / secrets BEFORE calling this function.
 *     The route layer runs scrubSecretsDeep on the spec + productState.
 *   - DataPoints with pii=true are surfaced by NAME + handlingNote only;
 *     their contents are never echoed.
 *   - Section text is regex-scrubbed for secret-shaped strings as a defense
 *     in depth (sk-/ghp_/AKIA/long base64).
 */

import type {
  Spec,
  ProductState,
  PlatformTarget,
  Need,
  Feature,
  Test,
  ADR,
  DataPoint,
  APIContract,
  Integration,
  NonGoal,
  Persona,
  Scenario,
  StanceBecauseClause,
  Assumption,
  Risk,
  UXFlow,
  Screen,
  TradeoffWeights,
  AgentSystem,
} from "@shared/schema";
import { TRADEOFF_AXES } from "@shared/schema";

// ---------------------------------------------------------------------------
// Public API
// ---------------------------------------------------------------------------

/**
 * Generate the full agent-handoff.md content for a finalized Spec.
 *
 * Pure: no LLM calls, no DB calls. Deterministic given the same inputs.
 *
 * @param spec — the structured spec (output of intake.finalize / spec generation)
 * @param productState — the project's productState (carries stance + tradeoff weights)
 * @returns Markdown string ready to paste into a coding agent
 */
export function generateHandoff(
  spec: Spec,
  productState?: ProductState | null,
): string {
  const sections: string[] = [];

  sections.push(renderHeader(spec));
  sections.push(renderBuildObjective(spec));
  sections.push(renderPersona(spec));
  sections.push(renderNonGoals(spec.nonGoals));
  sections.push(renderStanceAndWeights(productState ?? null));
  sections.push(renderADRs(spec.adrs));
  sections.push(renderDataModel(spec.dataPoints));
  sections.push(renderAPIContracts(spec.apiContracts));
  sections.push(renderIntegrations(spec.integrations));
  sections.push(renderAgentSystem(spec.agentSystem));
  sections.push(renderTestScaffolding(spec));
  sections.push(renderAskBeforePolicy());
  sections.push(renderNeedsAndFeatures(spec));
  sections.push(renderUXFlowsAndScreens(spec));
  sections.push(renderAssumptions(spec.assumptions));
  sections.push(renderRisks(spec.risks));

  const joined = sections
    .filter((s) => s && s.trim().length > 0)
    .join("\n\n");

  return scrubSecretShapedStrings(joined) + "\n";
}

/**
 * Verbatim ask-before policy. Exported so tests can assert on the exact lines.
 * Content matches the spec's Phase 5 security gate enumeration.
 */
export const ASK_BEFORE_POLICY_LINES: ReadonlyArray<string> = [
  "Storing PII or regulated data not declared in the spec.",
  "Choosing a paid external service.",
  "Introducing distributed services that aren't in the ADRs.",
  "Removing a P0 Need.",
  "Making any irreversible architecture decision with low confidence.",
  "Modifying the database schema in a non-additive way.",
  "Letting an agent use T4/T5 tools, external communication, production deploys, or destructive actions without explicit approval.",
];

// ---------------------------------------------------------------------------
// Section renderers
// ---------------------------------------------------------------------------

function renderHeader(spec: Spec): string {
  return `# Coding Agent Handoff — ${spec.productName}

> Generated by ProductPilot. Paste into Claude Code, Cursor, or Codex.
> Section order is prompt-cache-friendly: stable identity content first,
> dynamic specifics last. Edit the bottom freely without invalidating the
> cache for the upper sections.

**Platform target:** \`${spec.platformTarget}\``;
}

function renderBuildObjective(spec: Spec): string {
  const desc = spec.productDescription?.trim() || "_No product description captured._";
  return `## Build objective

${desc}`;
}

function renderPersona(spec: Spec): string {
  const lines: string[] = ["## Who this is for"];
  if (!spec.personas.length && !spec.scenarios.length) {
    lines.push("_No personas or scenarios captured yet._");
    return lines.join("\n");
  }
  for (const p of spec.personas) {
    lines.push("", `### ${p.name}`);
    if (p.trigger) lines.push(`**Trigger:** ${p.trigger}`);
    if (p.exclusions.length) {
      lines.push("", "**Who they are NOT:**");
      for (const e of p.exclusions) lines.push(`- ${e}`);
    }
    if (p.jobs.length) {
      lines.push("", "**Jobs to be done:**");
      for (const j of p.jobs) lines.push(`- ${j}`);
    }
  }
  if (spec.scenarios.length) {
    lines.push("", "### Outcome scenarios");
    for (const s of spec.scenarios) {
      const ctx = s.context ? `**Context:** ${s.context}\n` : "";
      const sig = s.successSignal ? `\n**Success signal:** ${s.successSignal}` : "";
      lines.push(`${ctx}**Goal:** ${s.goal}${sig}`);
    }
  }
  return lines.join("\n");
}

function renderNonGoals(nonGoals: NonGoal[]): string {
  if (!nonGoals.length) {
    return "## Non-goals\n\n_None declared._";
  }
  const items = nonGoals
    .map((n) => {
      const because = n.because?.trim() ? ` _Because: ${n.because}_` : "";
      return `- ${n.text}${because}`;
    })
    .join("\n");
  return `## Non-goals\n\n${items}`;
}

function renderStanceAndWeights(productState: ProductState | null): string {
  const lines: string[] = ["## Strategic frame"];
  const stance = productState?.stanceBecauseClauses ?? [];
  const weights = productState?.tradeoffWeights;

  lines.push("", "### Stance — because clauses");
  if (!stance.length) {
    lines.push("_No stance captured._");
  } else {
    for (const c of stance) {
      const label = c.category.replace(/_/g, " ");
      lines.push(`- **${label}** _(id: \`${c.id}\`)_: ${c.stance}`);
      if (c.because?.trim()) lines.push(`  _Because:_ ${c.because}`);
    }
  }

  lines.push("", "### Tradeoff weights (100-point allocation)");
  if (!weights) {
    lines.push("_No tradeoff weights allocated._");
  } else {
    for (const axis of TRADEOFF_AXES) {
      const v = (weights as TradeoffWeights)[axis];
      lines.push(`- \`${axis}\`: ${v}`);
    }
    lines.push(
      "",
      `**Unacceptable tradeoff:** \`${weights.unacceptable_tradeoff}\` — the user refuses to compromise this axis.`,
    );
  }
  return lines.join("\n");
}

function renderADRs(adrs: ADR[]): string {
  if (!adrs.length) {
    return "## Architecture decisions (ADRs)\n\n_None recorded._";
  }
  const lines: string[] = ["## Architecture decisions (ADRs)"];
  for (const a of adrs) {
    lines.push(
      "",
      `### ${a.id} — ${a.title}`,
      `**Reversibility:** ${a.reversibility}`,
      `**Context:** ${a.context}`,
      `**Decision:** ${a.decision}`,
    );
    if (a.consequences) lines.push(`**Consequences:** ${a.consequences}`);
    if (a.cites.length) lines.push(`**Cites:** ${a.cites.join(", ")}`);
  }
  return lines.join("\n");
}

function renderDataModel(dataPoints: DataPoint[]): string {
  if (!dataPoints.length) {
    return "## Data model\n\n_No data points captured._";
  }
  const lines: string[] = ["## Data model"];
  // PII items show NAME + handlingNote ONLY — never the raw description that
  // might leak source-of-truth values. The renderer treats pii=true as a
  // gate and elides the description even if present.
  for (const d of dataPoints) {
    if (d.pii === true) {
      const note = d.handlingNote?.trim()
        ? d.handlingNote
        : "TAG:UNRESOLVED — handlingNote required (linter blocks export).";
      lines.push(
        `- **${d.id}** ${d.name} \`${d.type}\` **(PII — handling note only)** — ${note}`,
      );
    } else {
      const desc = d.description ? ` — ${d.description}` : "";
      lines.push(`- **${d.id}** ${d.name} \`${d.type}\`${desc}`);
    }
  }
  return lines.join("\n");
}

function renderAPIContracts(apis: APIContract[]): string {
  if (!apis.length) {
    return "## API contracts\n\n_No APIs captured._";
  }
  const lines: string[] = ["## API contracts"];
  for (const a of apis) {
    lines.push("", `### \`${a.method} ${a.path}\` _(id: ${a.id})_`);
    if (a.description) lines.push(a.description);
    if (a.requestSchema) lines.push("**Request schema:**", "```", a.requestSchema, "```");
    if (a.responseSchema) lines.push("**Response schema:**", "```", a.responseSchema, "```");
    if (a.featureIds.length) lines.push(`_Serves features: ${a.featureIds.join(", ")}_`);
  }
  return lines.join("\n");
}

function renderIntegrations(items: Integration[]): string {
  if (!items.length) return "";
  const lines: string[] = ["## Integrations"];
  for (const i of items) {
    const auth = i.authMode ? ` (auth: ${i.authMode})` : "";
    lines.push(`- **${i.id}** ${i.name} — ${i.purpose}${auth}`);
  }
  return lines.join("\n");
}

function renderAgentSystem(agent: AgentSystem | undefined): string {
  if (!agent) return "";
  const lines: string[] = ["## Agent system contract"];

  if (agent.mission) lines.push("", `**Mission:** ${agent.mission}`);
  if (agent.builderScale) lines.push(`**Build scale:** \`${agent.builderScale}\``);
  lines.push(
    "",
    `**Topology:** \`${agent.architecturePattern ?? "TBD"}\``,
    `**Autonomy:** \`${agent.autonomyLevel ?? "TBD"}\``,
  );
  if (agent.stateOwner) lines.push(`**State owner:** ${agent.stateOwner}`);
  if (agent.stopCondition) lines.push(`**Stop condition:** ${agent.stopCondition}`);

  if (agent.systemBoundary.inScope.length || agent.systemBoundary.outOfScope.length) {
    lines.push("", "### Boundary");
    if (agent.systemBoundary.inScope.length) {
      lines.push("**In scope:**");
      for (const item of agent.systemBoundary.inScope) lines.push(`- ${item}`);
    }
    if (agent.systemBoundary.outOfScope.length) {
      lines.push("**Out of scope:**");
      for (const item of agent.systemBoundary.outOfScope) lines.push(`- ${item}`);
    }
  }

  if (agent.toolContracts.length) {
    lines.push("", "### Tool contracts");
    for (const tool of agent.toolContracts) {
      lines.push(`#### ${tool.id} — ${tool.name}`);
      lines.push(`- Purpose: ${tool.purpose}`);
      lines.push(`- Permission tier: \`${tool.permissionTier}\`${tool.requiresHumanApproval ? " (human approval required)" : ""}`);
      if (tool.allowedActions.length) lines.push(`- Allowed: ${tool.allowedActions.join("; ")}`);
      if (tool.forbiddenActions.length) lines.push(`- Forbidden: ${tool.forbiddenActions.join("; ")}`);
      if (tool.dataAccess) lines.push(`- Data access: ${tool.dataAccess}`);
      if (tool.sideEffects.length) lines.push(`- Side effects: ${tool.sideEffects.join("; ")}`);
      if (tool.auditLog) lines.push(`- Audit log: ${tool.auditLog}`);
      if (tool.rollbackPlan) lines.push(`- Rollback: ${tool.rollbackPlan}`);
      if (tool.failureMode) lines.push(`- Failure mode: ${tool.failureMode}`);
    }
  }

  if (agent.memoryPolicy || agent.researchProtocol) {
    lines.push("", "### Memory, sources, and evidence");
    if (agent.memoryPolicy) lines.push(`- Memory policy: ${agent.memoryPolicy}`);
    if (agent.researchProtocol?.sourcePolicy) lines.push(`- Source policy: ${agent.researchProtocol.sourcePolicy}`);
    if (agent.researchProtocol?.evidenceStandard) lines.push(`- Evidence standard: ${agent.researchProtocol.evidenceStandard}`);
    if (agent.researchProtocol?.confidencePolicy) lines.push(`- Confidence policy: ${agent.researchProtocol.confidencePolicy}`);
    if (agent.researchProtocol?.citationRequired) lines.push("- Citations required for factual claims.");
  }

  if (agent.uiProtocol) {
    lines.push("", "### UI and control surface");
    if (agent.uiProtocol.archetype) lines.push(`- UI archetype: \`${agent.uiProtocol.archetype}\``);
    if (agent.uiProtocol.designMode) lines.push(`- Design mode: ${agent.uiProtocol.designMode}`);
    for (const question of agent.uiProtocol.userResearchQuestions) {
      lines.push(`- User research question: ${question}`);
    }
  }

  if (agent.guardrails.length) {
    lines.push("", "### Guardrails");
    for (const guardrail of agent.guardrails) {
      lines.push(`- **${guardrail.id}** [${guardrail.severity}] Trigger: ${guardrail.trigger}; check: ${guardrail.check}; action: ${guardrail.action}`);
    }
  }

  if (agent.humanCheckpoints.length) {
    lines.push("", "### Human checkpoints");
    for (const checkpoint of agent.humanCheckpoints) lines.push(`- ${checkpoint}`);
  }

  if (agent.evaluations.length) {
    lines.push("", "### Evaluation scorecard");
    for (const evaluation of agent.evaluations) {
      lines.push(`- **${evaluation.id}** ${evaluation.name}: ${evaluation.metric}${evaluation.blocking ? " (blocking)" : ""}`);
    }
  }

  return lines.join("\n");
}

// ---------------------------------------------------------------------------
// Per-platform test scaffolding
//
// Section is required for the alpha-completion flow. Each platform emits a
// concise instruction block that ties P0 Needs → Tests by ID. The coding
// agent reads this and runs the matching framework.
// ---------------------------------------------------------------------------

interface PlatformScaffold {
  /** Heading after "Test scaffolding —" */
  heading: string;
  /** Top-level "Run X" instruction, with literal command formatting. */
  runInstruction: string;
  /** Where to place test files. */
  fileLocation: string;
  /** Extra notes (accessibility hooks, validators, etc.). */
  extraNotes: string;
  /** How to express a single Need→Test mapping for this platform. */
  needToTest(need: Need, test: Test): string;
}

const PLATFORM_SCAFFOLDS: Record<PlatformTarget, PlatformScaffold> = {
  web: {
    heading: "web (Vitest)",
    runInstruction: "Run `npm run test` (Vitest).",
    fileLocation: "Place tests under `<repo>/test/`. Each P0 Need maps to ≥1 test file.",
    extraNotes:
      "Use jsdom for component tests. Mock fetch via `vi.fn()`. " +
      "For E2E flows, Playwright is allowed — declare it in the test's `testFramework` field.",
    needToTest: (need, test) =>
      `Need \`${need.id}\` (${truncate(need.title, 50)}) → Test \`${test.id}\` → run \`npm run test -- ${test.id}\` or filter by description.`,
  },
  "vite-spa": {
    heading: "vite-spa (Vitest, optional Playwright)",
    runInstruction: "Run `npm run test` (Vitest preferred). Use Playwright only when an E2E browser is unavoidable.",
    fileLocation: "Place tests under `src/` colocated with the unit-under-test, suffix `.test.ts(x)`.",
    extraNotes:
      "Bundle-size budgets are first-class — every P0 feature should have a test that asserts no new top-level dep crosses the budget. " +
      "No SSR; assume a single static entry.",
    needToTest: (need, test) =>
      `Need \`${need.id}\` (${truncate(need.title, 50)}) → Test \`${test.id}\` → run \`npm run test -- ${test.id}\`.`,
  },
  ios: {
    heading: "ios (Swift Testing + XCTest)",
    runInstruction:
      "Run `xcodebuild test -scheme <Scheme>` or `swift test` (Swift Testing).",
    fileLocation:
      "Place tests in the `<Project>Tests/` group within the Xcode project. New files require `xcodegen generate` after adding (SourceKit ghosts otherwise).",
    extraNotes:
      "Use Swift Testing's `@Test` macro for new tests; XCTest stays for legacy compatibility. " +
      "Verify Dynamic Type (XS through XXXL) and full VoiceOver navigation per Need — accessibility is a build-time requirement, not a polish step.",
    needToTest: (need, test) =>
      `Need \`${need.id}\` (${truncate(need.title, 50)}) → Test \`${test.id}\` → run \`xcodebuild test -only-testing:<Scheme>Tests/${test.id}\`.`,
  },
  macos: {
    heading: "macos (Swift Testing + XCTest)",
    runInstruction:
      "Run `xcodebuild test -scheme <Scheme>` or `swift test` (Swift Testing).",
    fileLocation:
      "Place tests in the `<Project>Tests/` group. New files require `xcodegen generate` after adding.",
    extraNotes:
      "Use Swift Testing's `@Test` macro for new tests; XCTest stays for legacy compatibility. " +
      "Validate menu-bar, toolbar, and window-management conventions per HIG. " +
      "Keyboard-first apps must include a test for full menu-bar keyboard navigation.",
    needToTest: (need, test) =>
      `Need \`${need.id}\` (${truncate(need.title, 50)}) → Test \`${test.id}\` → run \`xcodebuild test -only-testing:<Scheme>Tests/${test.id}\`.`,
  },
  "claude-plugin": {
    heading: "claude-plugin (plugin-builder validators)",
    runInstruction:
      "Validate `plugin.json` via the manifest-validator. Test commands/skills/hooks via the matching plugin-builder validators (skill-validator, hook-validator, command-validator).",
    fileLocation:
      "Reference the plugin-builder skill at `~/dev/git-folder/RossLabs-AI-Toolkit/plugins/plugin-builder/`. " +
      "Each artifact (command, skill, hook) declares the validator that gates it.",
    extraNotes:
      "Every Test must declare ≥1 entry in `validatorRefs[]` — the linter warns when a claude-plugin test has none. " +
      "Run validators locally before committing — `claude plugins lint` against the package root.",
    needToTest: (need, test) => {
      const refs = test.validatorRefs.length
        ? test.validatorRefs.join(", ")
        : "no validatorRefs declared (linter warning)";
      return `Need \`${need.id}\` (${truncate(need.title, 50)}) → Test \`${test.id}\` → validators: ${refs}.`;
    },
  },
  "agent-system": {
    heading: "agent-system (golden tasks + safety evals)",
    runInstruction:
      "Run the agent's golden-task suite and safety/permission evals before marking the handoff ready.",
    fileLocation:
      "Place eval fixtures under `evals/` or the repo's existing test directory. Include tool-permission fixtures for every T3+ tool.",
    extraNotes:
      "Each P0 Need should map to a golden task. Every T4/T5 tool needs an approval-path test, audit-log check, and refusal test for missing permission or source evidence.",
    needToTest: (need, test) =>
      `Need \`${need.id}\` (${truncate(need.title, 50)}) → Test \`${test.id}\` → run golden task / safety eval \`${test.description}\`.`,
  },
};

function renderTestScaffolding(spec: Spec): string {
  const scaffold = PLATFORM_SCAFFOLDS[spec.platformTarget];
  if (!scaffold) {
    // Should never hit — schema enum is exhaustive — but degrade gracefully.
    return `## Test scaffolding\n\n_Unknown platform target \`${spec.platformTarget}\`._`;
  }

  const lines: string[] = [
    `## Test scaffolding — ${scaffold.heading}`,
    "",
    scaffold.runInstruction,
    "",
    scaffold.fileLocation,
    "",
    scaffold.extraNotes,
  ];

  // Need → Test mapping table. Only P0 needs surface here; lower priorities
  // are listed in the Needs section but not enforced in scaffolding.
  const p0Needs = spec.needs.filter((n) => n.priority === "P0");
  if (p0Needs.length) {
    lines.push("", "### P0 Need → Test mapping");
    for (const n of p0Needs) {
      const tests = spec.tests.filter((t) => t.needIds.includes(n.id));
      if (tests.length === 0) {
        lines.push(
          `- Need \`${n.id}\` (${truncate(n.title, 50)}) → **TAG:UNRESOLVED** — no Test references this Need (linter blocks export).`,
        );
      } else {
        for (const t of tests) {
          lines.push(`- ${scaffold.needToTest(n, t)}`);
        }
      }
    }
  } else {
    lines.push("", "_No P0 Needs declared. The coding agent should ask the user before scaffolding tests._");
  }

  return lines.join("\n");
}

function renderAskBeforePolicy(): string {
  const items = ASK_BEFORE_POLICY_LINES.map((line) => `- ${line}`).join("\n");
  return `## Ask before acting

The coding agent MUST escalate to the user before doing any of the following.
Do not infer, do not "use best judgment" — pause and ask.

${items}

If a low-confidence assumption is the only way to proceed, name the
assumption explicitly and confirm before writing code.`;
}

function renderNeedsAndFeatures(spec: Spec): string {
  const lines: string[] = ["## Needs and features"];

  if (spec.needs.length === 0 && spec.features.length === 0) {
    lines.push("", "_No Needs or Features captured yet._");
    return lines.join("\n");
  }

  lines.push("", "### Needs");
  if (!spec.needs.length) {
    lines.push("_None._");
  } else {
    for (const n of spec.needs) {
      lines.push(formatNeed(n));
    }
  }

  lines.push("", "### Features");
  if (!spec.features.length) {
    lines.push("_None._");
  } else {
    for (const f of spec.features) {
      lines.push(formatFeature(f));
    }
  }

  return lines.join("\n");
}

function formatNeed(n: Need): string {
  const pri = n.priority ? `[${n.priority}] ` : "";
  const desc = n.description ? ` — ${n.description}` : "";
  return `- **${n.id}** ${pri}${n.title}${desc}`;
}

function formatFeature(f: Feature): string {
  const pri = f.priority ? `[${f.priority}] ` : "";
  const refs = f.needIds.length ? ` (serves ${f.needIds.join(", ")})` : "";
  const ac = f.acceptanceCriteria.length
    ? `\n  - Acceptance:\n${f.acceptanceCriteria.map((c) => `    - ${c}`).join("\n")}`
    : "";
  return `- **${f.id}** ${pri}${f.title}${refs}${ac}`;
}

function renderUXFlowsAndScreens(spec: Spec): string {
  if (!spec.uxFlows.length && !spec.screens.length) return "";
  const lines: string[] = ["## UX flows and screens"];
  if (spec.uxFlows.length) {
    lines.push("", "### Flows");
    for (const f of spec.uxFlows) {
      const steps = f.steps.length
        ? f.steps.map((s, i) => `  ${i + 1}. ${s}`).join("\n")
        : "  _No steps._";
      const screens = f.screenIds.length ? `  - Screens: ${f.screenIds.join(", ")}` : "";
      lines.push(`#### ${f.name} _(${f.id})_`);
      lines.push(steps);
      if (screens) lines.push(screens);
    }
  }
  if (spec.screens.length) {
    lines.push("", "### Screens");
    for (const s of spec.screens) {
      const states = s.states.length ? `  - States: ${s.states.join(", ")}` : "";
      const primary = s.primaryAction ? `  - Primary action: ${s.primaryAction}` : "";
      lines.push(`- **${s.id}** ${s.name} — ${s.purpose}`);
      if (primary) lines.push(primary);
      if (states) lines.push(states);
    }
  }
  return lines.join("\n");
}

function renderAssumptions(items: Assumption[]): string {
  if (!items.length) return "";
  const list = items.map((a) => `- _(${a.confidence})_ ${a.text}`).join("\n");
  return `## Assumptions\n\n${list}`;
}

function renderRisks(items: Risk[]): string {
  if (!items.length) return "";
  const list = items
    .map((r) => {
      const mit = r.mitigation ? ` Mitigation: ${r.mitigation}` : "";
      return `- _(L:${r.likelihood} I:${r.impact})_ ${r.text}.${mit}`;
    })
    .join("\n");
  return `## Risks\n\n${list}`;
}

// ---------------------------------------------------------------------------
// Helpers
// ---------------------------------------------------------------------------

function truncate(s: string, n: number): string {
  if (typeof s !== "string") return "";
  return s.length <= n ? s : `${s.slice(0, n - 1)}…`;
}

/**
 * Defense-in-depth: scrub anything that looks like a secret. The route layer
 * runs scrubSecretsDeep on the spec + productState before invoking us, but a
 * stray match here means the original scrubber missed something — better to
 * redact than leak.
 */
const SECRET_PATTERNS: RegExp[] = [
  /\bsk-[A-Za-z0-9_-]{16,}\b/g,
  /\bghp_[A-Za-z0-9]{24,}\b/g,
  /\bgho_[A-Za-z0-9]{24,}\b/g,
  /\bAKIA[0-9A-Z]{12,20}\b/g,
  /\baws_secret_access_key\s*[=:]\s*[A-Za-z0-9/+]{30,}\b/gi,
  /\b[A-Za-z0-9_-]{40,}\b\.[A-Za-z0-9_-]{8,}\.[A-Za-z0-9_-]{8,}\b/g, // jwt-shaped
];

function scrubSecretShapedStrings(s: string): string {
  let out = s;
  for (const re of SECRET_PATTERNS) {
    out = out.replace(re, "[REDACTED]");
  }
  return out;
}

// Re-export the scaffold map for tests that want to assert on per-platform
// content without re-deriving the heading/run-instruction text.
export const __platformScaffolds = PLATFORM_SCAFFOLDS;
